-- ==============================================================================
-- FASE 2 / SOTTO-FASE A: SCHEMA NORMALIZZATO GRIKO
-- Progetto Supabase: xhpcztzisqdzqiwrojvl
-- Eseguire questo script nel SQL Editor della Dashboard Supabase:
-- https://supabase.com/dashboard/project/xhpcztzisqdzqiwrojvl/sql/new
-- ==============================================================================

-- 1. Tabella lessons (73 lezioni)
CREATE TABLE IF NOT EXISTS public.lessons (
    id INTEGER PRIMARY KEY,
    titolo TEXT NOT NULL,
    categoria TEXT,
    genere TEXT,
    desinenza TEXT,
    video_index INTEGER
);

-- 2. Tabella rules (158 regole grammaticali)
CREATE TABLE IF NOT EXISTS public.rules (
    id INTEGER PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
    regola_testo TEXT NOT NULL
);

-- 3. Tabella lexemes (voci uniche di dizionario: parola_griko + parola_italiano)
CREATE TABLE IF NOT EXISTS public.lexemes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parola_griko TEXT NOT NULL,
    parola_italiano TEXT NOT NULL,
    CONSTRAINT uq_lexemes_griko_italiano UNIQUE (parola_griko, parola_italiano)
);

CREATE INDEX IF NOT EXISTS idx_lexemes_griko ON public.lexemes (parola_griko);
CREATE INDEX IF NOT EXISTS idx_lexemes_italiano ON public.lexemes (parola_italiano);

-- 4. Tabella occurrences (collegamento N:N tra vocabolario e lezioni)
CREATE TABLE IF NOT EXISTS public.occurrences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lexeme_id BIGINT NOT NULL REFERENCES public.lexemes(id) ON DELETE CASCADE,
    lesson_id INTEGER NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE,
    CONSTRAINT uq_occurrences_lexeme_lesson UNIQUE (lexeme_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS idx_occurrences_lexeme_id ON public.occurrences (lexeme_id);
CREATE INDEX IF NOT EXISTS idx_occurrences_lesson_id ON public.occurrences (lesson_id);

-- 5. Rimuove la vecchia tabella vocabulary non normalizzata (vuota)
DROP TABLE IF EXISTS public.vocabulary;

-- 6. Abilitazione Row Level Security (RLS) su tutte le tabelle
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lexemes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.occurrences ENABLE ROW LEVEL SECURITY;

-- 7. Policy di lettura pubblica per chiunque (anon / publishable key)
DROP POLICY IF EXISTS "Allow public read on lessons" ON public.lessons;
CREATE POLICY "Allow public read on lessons"
    ON public.lessons FOR SELECT
    TO public
    USING (true);

DROP POLICY IF EXISTS "Allow public read on rules" ON public.rules;
CREATE POLICY "Allow public read on rules"
    ON public.rules FOR SELECT
    TO public
    USING (true);

DROP POLICY IF EXISTS "Allow public read on lexemes" ON public.lexemes;
CREATE POLICY "Allow public read on lexemes"
    ON public.lexemes FOR SELECT
    TO public
    USING (true);

DROP POLICY IF EXISTS "Allow public read on occurrences" ON public.occurrences;
CREATE POLICY "Allow public read on occurrences"
    ON public.occurrences FOR SELECT
    TO public
    USING (true);
