-- ==============================================================================
-- Tabella per materiale libero da copyright (tradizione orale, grammatica, proverbi)
-- estratto da ciuricepedi.it. Esclude opere d'autore, saggi, media protetti.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.testi_liberi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    titolo TEXT NOT NULL,
    categoria TEXT NOT NULL,        -- fiaba | canto | proverbio | filastrocca | grammatica | vocabolario | morolòj
    testo TEXT NOT NULL,
    url_fonte TEXT NOT NULL,
    licenza TEXT NOT NULL DEFAULT 'pubblico_dominio_tradizione_orale',
    creato_il TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_testi_liberi_categoria ON public.testi_liberi (categoria);

ALTER TABLE public.testi_liberi ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on testi_liberi" ON public.testi_liberi;
CREATE POLICY "Allow public read on testi_liberi"
    ON public.testi_liberi FOR SELECT
    TO public
    USING (true);
