-- ==============================================================================
-- Corso Sistematico di Carmine Greco — schema normalizzato
-- Stessa struttura del corso di Daniele Palma (lessons/rules/lexemes/occurrences):
-- ogni lezione e' scomposta in regole grammaticali e vocabolario indicizzato,
-- non un dump della trascrizione grezza.
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.carmine_lessons (
    id INTEGER PRIMARY KEY,               -- = "order" della lezione (1..24)
    video_id TEXT NOT NULL UNIQUE,
    titolo TEXT NOT NULL,
    categoria TEXT NOT NULL,              -- fonetica | nomi | aggettivi | pronomi_numerali | invariabili | verbi
    categoria_label TEXT NOT NULL,
    durata TEXT NOT NULL,
    sommario TEXT NOT NULL,
    proverbio TEXT,
    youtube_url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.carmine_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES public.carmine_lessons(id) ON DELETE CASCADE,
    regola_testo TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.carmine_lexemes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parola_griko TEXT NOT NULL,
    parola_italiano TEXT NOT NULL,
    CONSTRAINT uq_carmine_lexemes_griko_italiano UNIQUE (parola_griko, parola_italiano)
);

CREATE INDEX IF NOT EXISTS idx_carmine_lexemes_griko ON public.carmine_lexemes (parola_griko);

CREATE TABLE IF NOT EXISTS public.carmine_occurrences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lexeme_id BIGINT NOT NULL REFERENCES public.carmine_lexemes(id) ON DELETE CASCADE,
    lesson_id INTEGER NOT NULL REFERENCES public.carmine_lessons(id) ON DELETE CASCADE,
    CONSTRAINT uq_carmine_occurrences_lexeme_lesson UNIQUE (lexeme_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS idx_carmine_occurrences_lesson ON public.carmine_occurrences (lesson_id);
CREATE INDEX IF NOT EXISTS idx_carmine_occurrences_lexeme ON public.carmine_occurrences (lexeme_id);

CREATE INDEX IF NOT EXISTS idx_carmine_rules_lesson ON public.carmine_rules (lesson_id);

ALTER TABLE public.carmine_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carmine_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carmine_lexemes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carmine_occurrences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on carmine_lessons" ON public.carmine_lessons;
CREATE POLICY "Allow public read on carmine_lessons" ON public.carmine_lessons FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public read on carmine_rules" ON public.carmine_rules;
CREATE POLICY "Allow public read on carmine_rules" ON public.carmine_rules FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public read on carmine_lexemes" ON public.carmine_lexemes;
CREATE POLICY "Allow public read on carmine_lexemes" ON public.carmine_lexemes FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow public read on carmine_occurrences" ON public.carmine_occurrences;
CREATE POLICY "Allow public read on carmine_occurrences" ON public.carmine_occurrences FOR SELECT TO public USING (true);
